# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_content', models.CharField(max_length=200)),
                ('acquired_date', models.DateTimeField(verbose_name='Download end date.')),
            ],
        ),
        migrations.CreateModel(
            name='RootUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('root_url', models.CharField(max_length=2000)),
                ('start_date', models.DateTimeField(verbose_name='Download starting date.')),
                ('stop_date', models.DateTimeField(verbose_name='Download end date.')),
                ('last_update_date', models.DateTimeField(verbose_name='Download last update.')),
            ],
        ),
        migrations.AddField(
            model_name='itemurl',
            name='item_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.RootUrl'),
        ),
    ]
